/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin.login'
import { Route as SuperAdminDashboardRouteImport } from './routes/super-admin.dashboard'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'
import { Route as ClientLoginRouteImport } from './routes/client.login'
import { Route as ClientDashboardRouteImport } from './routes/client.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin/login',
  path: '/super-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminDashboardRoute = SuperAdminDashboardRouteImport.update({
  id: '/super-admin/dashboard',
  path: '/super-admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client/login',
  path: '/client/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/client/dashboard',
  path: '/client/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/login': typeof ClientLoginRoute
  '/site/$slug': typeof SiteSlugRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/login': typeof ClientLoginRoute
  '/site/$slug': typeof SiteSlugRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/login': typeof ClientLoginRoute
  '/site/$slug': typeof SiteSlugRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client/dashboard'
    | '/client/login'
    | '/site/$slug'
    | '/super-admin/dashboard'
    | '/super-admin/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client/dashboard'
    | '/client/login'
    | '/site/$slug'
    | '/super-admin/dashboard'
    | '/super-admin/login'
  id:
    | '__root__'
    | '/'
    | '/client/dashboard'
    | '/client/login'
    | '/site/$slug'
    | '/super-admin/dashboard'
    | '/super-admin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientLoginRoute: typeof ClientLoginRoute
  SiteSlugRoute: typeof SiteSlugRoute
  SuperAdminDashboardRoute: typeof SuperAdminDashboardRoute
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/login': {
      id: '/super-admin/login'
      path: '/super-admin/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/dashboard': {
      id: '/super-admin/dashboard'
      path: '/super-admin/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof SuperAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/login': {
      id: '/client/login'
      path: '/client/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientDashboardRoute: ClientDashboardRoute,
  ClientLoginRoute: ClientLoginRoute,
  SiteSlugRoute: SiteSlugRoute,
  SuperAdminDashboardRoute: SuperAdminDashboardRoute,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
