/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin.login'
import { Route as SuperAdminDashboardRouteImport } from './routes/super-admin.dashboard'
import { Route as ClientLoginRouteImport } from './routes/client.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin/login',
  path: '/super-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminDashboardRoute = SuperAdminDashboardRouteImport.update({
  id: '/super-admin/dashboard',
  path: '/super-admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client/login',
  path: '/client/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client/login': typeof ClientLoginRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client/login': typeof ClientLoginRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client/login': typeof ClientLoginRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client/login'
    | '/super-admin/dashboard'
    | '/super-admin/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/client/login' | '/super-admin/dashboard' | '/super-admin/login'
  id:
    | '__root__'
    | '/'
    | '/client/login'
    | '/super-admin/dashboard'
    | '/super-admin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientLoginRoute: typeof ClientLoginRoute
  SuperAdminDashboardRoute: typeof SuperAdminDashboardRoute
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/login': {
      id: '/super-admin/login'
      path: '/super-admin/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/dashboard': {
      id: '/super-admin/dashboard'
      path: '/super-admin/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof SuperAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/login': {
      id: '/client/login'
      path: '/client/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientLoginRoute: ClientLoginRoute,
  SuperAdminDashboardRoute: SuperAdminDashboardRoute,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
